name: test

on:
  release:
    types: [published]
  push:
    branches:
      - master
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Update feeds
      run: |
        df -h
        free -h
        lsusb||true
        lspci||true
        lscpu||cat /proc/cpuinfo||true
        
